<?php

/**
 * @file
 * Contains site_info_alter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function site_info_alter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the site_info_alter module.
    case 'help.page.site_info_alter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Alter Site info form') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function site_info_alter_theme() {
  return [
    'site_info_alter' => [
      'render element' => 'children',
    ],
  ];
}
